"""platformctl validate — the enforcement table from docs/service-contract.md.

 # | rule                                    | mechanism
 1 | owning team must exist                  | validate_owner_exists (this module)
 2 | tier is 1/2/3                            | schema.ServiceManifest.tier (Literal)
 3 | immutable image tag                      | validate_image_tag (this module)
 4 | resource requests and limits present     | schema.Resources (required fields)
   | limits must be >= requests               | validate_resource_limits (this module)
 5 | readiness and liveness probes            | schema.Probes (required fields)
 6 | SLO with an explicit window               | schema.Slo (required fields)
 7 | a dashboard                               | generated by `platformctl render`
   |                                           | (out of scope this session — render is not implemented)
 8 | a runbook that exists                     | validate_runbook_exists (this module)
 9 | rollback strategy is gitops-revert        | schema.Operations.rollback (Literal)
10 | no drift between manifest and artifacts   | CI: `platformctl render` + `git diff --exit-code`
   |                                           | (out of scope this session — render is not implemented)
11 | name is a valid RFC 1123 label, <=53 chars | schema.ServiceManifest.name (Field pattern + max_length)
12 | owning team is a valid label value        | teams.load_teams (raises InvalidTeamNameError)
13 | availability SLO is strictly in (0, 100)  | schema.Slo.availability (Field gt/lt)

Rules 7 and 10 are satisfied structurally by the render/CI pipeline, not by
anything `validate` can check from the manifest alone, so there is nothing
for `validate` to enforce for them until `render` exists.
"""

import re
from pathlib import Path

from pydantic import ValidationError
import yaml

from platformctl.quantities import parse_cpu, parse_memory
from platformctl.schema import ServiceManifest

_IMMUTABLE_TAG_RE = re.compile(
    r"^v?\d+\.\d+\.\d+(-[0-9A-Za-z.]+)?$"  # semver, e.g. v1.4.2
    r"|^[0-9a-f]{40}$"  # full git sha
    r"|^sha256:[0-9a-f]{64}$"  # image digest
)


def validate_image_tag(manifest: ServiceManifest) -> list[str]:
    """Rule 3: image.tag must be immutable — no `latest`, no unpinned tags."""
    tag = manifest.image.tag
    if tag.strip().lower() == "latest":
        return ["image.tag must not be 'latest'"]
    if not _IMMUTABLE_TAG_RE.match(tag):
        return [
            f"image.tag '{tag}' is not an immutable tag "
            "(expected a semver tag like v1.4.2 or a full sha/digest)"
        ]
    return []


def validate_resource_limits(manifest: ServiceManifest) -> list[str]:
    """Rule 4: resource limits must be >= requests."""
    errors: list[str] = []
    requests = manifest.runtime.resources.requests
    limits = manifest.runtime.resources.limits

    try:
        if parse_cpu(limits.cpu) < parse_cpu(requests.cpu):
            errors.append(
                f"runtime.resources.limits.cpu ({limits.cpu}) is less than "
                f"requests.cpu ({requests.cpu})"
            )
    except ValueError:
        errors.append(
            f"runtime.resources.{{requests,limits}}.cpu is not a valid quantity "
            f"('{requests.cpu}' / '{limits.cpu}')"
        )

    try:
        if parse_memory(limits.memory) < parse_memory(requests.memory):
            errors.append(
                f"runtime.resources.limits.memory ({limits.memory}) is less than "
                f"requests.memory ({requests.memory})"
            )
    except ValueError:
        errors.append(
            f"runtime.resources.{{requests,limits}}.memory is not a valid quantity "
            f"('{requests.memory}' / '{limits.memory}')"
        )

    return errors


def validate_owner_exists(manifest: ServiceManifest, teams: set[str]) -> list[str]:
    """Rule 1: owner must be a team declared in platform/teams.yaml."""
    if manifest.owner not in teams:
        return [f"owner '{manifest.owner}' is not a known team (see platform/teams.yaml)"]
    return []


def validate_runbook_exists(manifest: ServiceManifest, root: Path) -> list[str]:
    """Rule 8: operations.runbook must point at a file that exists."""
    runbook_path = root / manifest.operations.runbook
    if not runbook_path.is_file():
        return [f"operations.runbook '{manifest.operations.runbook}' does not exist"]
    return []


def validate_manifest(
    manifest_path: Path, teams: set[str], root: Path
) -> tuple[ServiceManifest | None, list[str]]:
    """Parse and validate a single service.yaml. Returns (manifest, errors).

    manifest is None if the file could not even be parsed against the schema.
    """
    try:
        raw = yaml.safe_load(manifest_path.read_text())
    except yaml.YAMLError as exc:
        return None, [f"invalid YAML: {exc}"]

    try:
        manifest = ServiceManifest.model_validate(raw)
    except ValidationError as exc:
        errors = [
            "{}: {}".format(".".join(str(p) for p in err["loc"]), err["msg"])
            for err in exc.errors()
        ]
        return None, errors

    errors = [
        *validate_owner_exists(manifest, teams),
        *validate_image_tag(manifest),
        *validate_resource_limits(manifest),
        *validate_runbook_exists(manifest, root),
    ]
    return manifest, errors
