apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.name }}
    app.kubernetes.io/managed-by: platformctl
    platform.io/owner: {{ .Values.owner }}
    platform.io/tier: "{{ .Values.tier }}"
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.name }}
  ports:
    - name: http
      port: {{ .Values.runtime.port }}
      targetPort: http
