apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    platform.io/owner: platform-team
    platform.io/tier: '2'
  name: demo-api
  namespace: argocd
spec:
  destination:
    namespace: demo-api
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values/demo-api.yaml
    path: helm/service
    repoURL: https://github.com/amirmarcel/platform-zero.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
