apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    platform.io/owner: platform-team
  name: observability
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    path: observability
    repoURL: https://github.com/example/platform-zero.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
